### ISSUE TITLE
Lightweight X server.

### ISSUE THREAD

**Issue by el3ctr0lyte** [vvaltchev/tilck#80] opened 2021-08-05 12:10 UTC
There are lightweight x server implementations like Xfree86 and Nano-x that could maybe be added as extra stuff that you have to configure with the build scripts. It would be impressive to see how well this would work and what applications would run. Although i think you would probably also need gtk and qt5 which would bloat it a bit. Just something to think about.

**Comment by vvaltchev** [comment] 2021-08-05 13:20
Hi!
I've answered to your question in Github discussions section, as this is not a bug report.
Let's continue the conversation here: https://github.com/vvaltchev/tilck/discussions/81

I'm closing this non-issue.

**Closed by vvaltchev** 2021-08-05 13:20 UTC
